# Generated by Django 4.0 on 2021-12-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenomClient', models.CharField(max_length=200, null=True)),
                ('nomClient', models.CharField(max_length=200, null=True)),
                ('ageClient', models.IntegerField(null=True)),
                ('emailClient', models.CharField(max_length=200, null=True)),
                ('adresseClient', models.CharField(max_length=600, null=True)),
            ],
        ),
    ]
