# Generated by Django 4.0 on 2021-12-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telClient',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
