# Generated by Django 4.0 on 2021-12-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe',
            old_name='email',
            new_name='emailEmploye',
        ),
        migrations.AddField(
            model_name='employe',
            name='telEmploye',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
