# Generated by Django 4.0 on 2022-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_employe_mdpemploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='pseudoEmploye',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
