# Generated by Django 4.0 on 2022-02-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_employe_pseudoemploye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='pseudoEmploye',
            field=models.CharField(max_length=50),
        ),
    ]
