# Generated by Django 4.0 on 2022-02-24 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0005_alter_employe_pseudoemploye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='pseudoEmploye',
        ),
    ]
